import { UserButton } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { useSeedNewUser } from "~/hooks/use-seed-new-user";

import { api } from "~/utils/api";

export default function Home() {
  const { data: userData, isLoading: userDataIsLoading } = api.user.get.useQuery();

  useSeedNewUser({ data: userData, isLoading: userDataIsLoading });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Welcome to <span className="text-[hsl(280,100%,70%)]">CarKaki</span> !!
          </h1>
        </div>
      </main>
    </>
  );
}
