import { UserButton } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image"
import { useSeedNewUser } from "~/hooks/use-seed-new-user";
import { Button } from "~/components/ui/button";

import { api } from "~/utils/api";

export default function Home() {
  const { data: userData, isLoading: userDataIsLoading } = api.user.get.useQuery();

  useSeedNewUser({ data: userData, isLoading: userDataIsLoading });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen">
      {/* Left column (blue) */}
      <div className="flex-1 bg-blue-500 flex flex-col justify-center items-center text-white p-8">
        <div className="flex items-center space-x-8">
          <h1 className="text-8xl font-bold">CarKaki</h1>
          <svg width="179" height="195" viewBox="0 0 179 195" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M156.625 65.0004L141.708 81.2504M141.708 81.2504L130.521 51.1879C129.466 48.1112 127.58 45.4551 125.111 43.5695C122.643 41.6839 119.708 40.6575 116.693 40.6254H62.65C59.6108 40.5493 56.6227 41.4867 54.0861 43.312C51.5495 45.1373 49.5854 47.7634 48.4568 50.8385L37.2917 81.2504M141.708 81.2504H37.2917M141.708 81.2504C149.947 81.2504 156.625 88.5254 156.625 97.5001V130C156.625 138.975 149.947 146.25 141.708 146.25M37.2917 81.2504L22.375 65.0004M37.2917 81.2504C29.0534 81.2504 22.375 88.5254 22.375 97.5001V130C22.375 138.975 29.0534 146.25 37.2917 146.25M52.2083 113.75H52.2829M126.792 113.75H126.866M141.708 146.25H37.2917M141.708 146.25V162.5M37.2917 146.25V162.5" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            <path d="M74 117.712C75.7072 119.419 78.3327 125.266 80.8465 125.414C84.8626 125.65 88.673 127.126 92.8278 127.126C98.6508 127.126 104.743 121.334 106.521 116" stroke="white" stroke-width="3" stroke-linecap="round"/>
            <path d="M51.7941 113.319C51.7941 114.656 52.6211 117.655 53.5868 114.865C54.412 112.481 53.1075 113.876 51.7941 113.876" stroke="white" stroke-width="3" stroke-linecap="round"/>
            <path d="M126.345 113.876C126.345 116.722 129.773 111.884 125.789 113.876" stroke="white" stroke-width="3" stroke-linecap="round"/>
          </svg>
        </div>
      </div>

      {/* Right column (white) */}
      <div className="flex-1 bg-white flex flex-col justify-center items-center p-8">
          <div className="max-w-md w-full">
            <p className="text-xl text-blue-500 text-center font-semibold mb-8">
              Integrating real-time data from the Urban Redevelopment Authority (URA) API to provide users with parking availability, rates, and geolocation-based navigation
            </p>

            {
              userData ? (
                <>
                  <Button className="w-full bg-blue-500 text-white hover:bg-blue-600" size="lg">
                    Sign in
                  </Button>
                  <p className="text-sm text-center mt-4">
                    No account? <a href="#" className="text-blue-500 hover:underline">Sign up.</a>
                  </p>
                </>
              ) : (
                 (
                  <Button className="w-full bg-blue-500 text-white hover:bg-blue-600" size="lg">
                    Let's go!
                  </Button>
                )
              )
            }
          </div>
        </div>

        {/* User button in the top-right corner */}
        <div className="absolute top-4 right-4">
          <UserButton afterSignOutUrl="/" />
        </div>
    </main>
    </>
  );
}
